CREATE TABLE [dbo].[JobStates]
(
    [JobStateId] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    [StateName] NVARCHAR(255) NOT NULL,
    [CreatedBy] NVARCHAR(255) NOT NULL DEFAULT(SUSER_SNAME()),
    [CreatedDateTime] DATETIME NOT NULL DEFAULT(GETDATE()),
    [LastModifiedBy] NVARCHAR(255) NOT NULL DEFAULT(SUSER_SNAME()),
    [LastModifiedDateTime] DATETIME NOT NULL DEFAULT(GETDATE()),
    CONSTRAINT [PK_JobStateId] PRIMARY KEY ([JobStateId])
)
