CREATE TABLE [dbo].[Jobs]
(
    [JobId] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    [JobName] NVARCHAR(255) NOT NULL,
    [MachineName] NVARCHAR(255) NOT NULL,
    [JobStateId] UNIQUEIDENTIFIER NOT NULL,
    [JobTrigger] BIT NOT NULL,
    [JobOrder] INT NOT NULL,
    [CreatedBy] NVARCHAR(255) NOT NULL DEFAULT(SUSER_SNAME()),
    [CreatedDateTime] DATETIME NOT NULL DEFAULT(GETDATE()),
    [LastModifiedBy] NVARCHAR(255) NOT NULL DEFAULT(SUSER_SNAME()),
    [LastModifiedDateTime] DATETIME NOT NULL DEFAULT(GETDATE()),
    CONSTRAINT [PK_Jobs] PRIMARY KEY ([JobId]),
    CONSTRAINT [UC_Jobs] UNIQUE ([JobName], [MachineName]),
    CONSTRAINT [FK_Jobs_JobStates] FOREIGN KEY ([JobStateId]) REFERENCES [JobStates]([JobStateId])
)
